baseurl: ''
url: https://www.naprok.com  
enforce_ssl: www.naprok.com

sass:
  style: :compressed

title: IT Outstaffing, Software Outsourcing, Web Application Development, Custom Software Development Company | Naprok Outstaffing
description:
  Staff your team easily
